// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var EventRegister, LRUCache, PagedAsyncTableModel, Painter, ScrollBarProxy, SyncTableModel, TableModel, TableView, binary_search, bound, closest, cumsum, distance, fattable, getEventPointerCoordinates, getEventTouches, k, ns, prefixedTransformCssKey, smallest_diff_subsequence, v,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  cumsum = function(arr) {
    var cs, s, x, _i, _len;
    cs = [0.0];
    s = 0.0;
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      x = arr[_i];
      s += x;
      cs.push(s);
    }
    return cs;
  };

  bound = function(x, m, M) {
    if (x < m) {
      return m;
    } else if (x > M) {
      return M;
    } else {
      return x;
    }
  };

  binary_search = function(arr, x) {
    var a, b, m, v;
    if (arr[0] > x) {
      return 0;
    } else {
      a = 0;
      b = arr.length;
      while (a + 2 < b) {
        m = (a + b) / 2 | 0;
        v = arr[m];
        if (v < x) {
          a = m;
        } else if (v > x) {
          b = m;
        } else {
          return m;
        }
      }
      return a;
    }
  };

  distance = function(a1, a2) {
    return Math.abs(a2 - a1);
  };

  closest = function() {
    var d, d_, res, vals, x, x_, _i, _len;
    x = arguments[0], vals = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    d = Infinity;
    res = void 0;
    for (_i = 0, _len = vals.length; _i < _len; _i++) {
      x_ = vals[_i];
      d_ = distance(x, x_);
      if (d_ < d) {
        d = d_;
        res = x_;
      }
    }
    return res;
  };

  smallest_diff_subsequence = function(arr, scrollWidth) {
    var l, start;
    l = 1;
    start = 0;
    while (start + l < arr.length) {
      if (arr[start + l] - arr[start] > scrollWidth) {
        start += 1;
      } else {
        l += 1;
      }
    }
    return l;
  };

  prefixedTransformCssKey = (function() {
    var el, testKey, _i, _len, _ref;
    el = document.createElement("div");
    _ref = ["transform", "WebkitTransform", "MozTransform", "OTransform", "MsTransform"];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      testKey = _ref[_i];
      if (el.style[testKey] !== void 0) {
        return testKey;
      }
    }
  })();

  LRUCache = (function() {
    function LRUCache(size) {
      this.size = size != null ? size : 100;
      this.data = {};
      this.lru_keys = [];
    }

    LRUCache.prototype.has = function(k) {
      return this.data.hasOwnProperty(k);
    };

    LRUCache.prototype.get = function(k) {
      return this.data[k];
    };

    LRUCache.prototype.set = function(k, v) {
      var idx, removeKey;
      idx = this.lru_keys.indexOf(k);
      if (idx >= 0) {
        this.lru_keys.splice(idx, 1);
      }
      this.lru_keys.push(k);
      if (this.lru_keys.length >= this.size) {
        removeKey = this.lru_keys.shift();
        delete this.data[removeKey];
      }
      return this.data[k] = v;
    };

    return LRUCache;

  })();

  getEventPointerCoordinates = function(event) {
    var c, e, touches;
    c = {
      x: 0,
      y: 0
    };
    if (event) {
      touches = event.touches && event.touches.length ? event.touches : [event];
      e = event.changedTouches && event.changedTouches[0] || touches[0];
      if (e) {
        c.x = e.clientX || e.pageX || 0;
        c.y = e.clientY || e.pageY || 0;
      }
    }
    return c;
  };

  getEventTouches = function(e) {
    if (e.touches && e.touches.length) {
      return e.touches;
    } else {
      return [
        {
          pageX: e.pageX,
          pageY: e.pageY
        }
      ];
    }
  };

  TableModel = (function() {
    function TableModel() {}

    TableModel.prototype.hasCell = function(i, j) {
      return false;
    };

    TableModel.prototype.hasColumnHeader = function(j) {
      return false;
    };

    TableModel.prototype.hasRowHeader = function(i) {
      return false;
    };

    TableModel.prototype.getCell = function(i, j, cb) {
      if (cb == null) {
        cb = (function() {});
      }
      return cb("getCell not implemented");
    };

    TableModel.prototype.getColumnHeader = function(j, cb) {
      if (cb == null) {
        cb = (function() {});
      }
      return cb("getColumnHeader not implemented");
    };

    TableModel.prototype.getRowHeader = function(i, cb) {
      if (cb == null) {
        cb = (function() {});
      }
      return cb("getRowHeader not implemented");
    };

    return TableModel;

  })();

  SyncTableModel = (function(_super) {
    __extends(SyncTableModel, _super);

    function SyncTableModel() {
      return SyncTableModel.__super__.constructor.apply(this, arguments);
    }

    SyncTableModel.prototype.getCellSync = function(i, j) {
      return i + "," + j;
    };

    SyncTableModel.prototype.getColumnHeaderSync = function(j) {
      return "col " + j;
    };

    SyncTableModel.prototype.getRowHeaderSync = function(i) {
      return "row " + i;
    };

    SyncTableModel.prototype.hasCell = function(i, j) {
      return true;
    };

    SyncTableModel.prototype.hasColumnHeader = function(j) {
      return true;
    };

    SyncTableModel.prototype.hasRowHeader = function(i) {
      return true;
    };

    SyncTableModel.prototype.getCell = function(i, j, cb) {
      if (cb == null) {
        cb = (function() {});
      }
      return cb(this.getCellSync(i, j));
    };

    SyncTableModel.prototype.getColumnHeader = function(j, cb) {
      if (cb == null) {
        cb = (function() {});
      }
      return cb(this.getColumnHeaderSync(j));
    };

    SyncTableModel.prototype.getRowHeader = function(i, cb) {
      if (cb == null) {
        cb = (function() {});
      }
      return cb(this.getRowHeaderSync(i));
    };

    return SyncTableModel;

  })(TableModel);

  PagedAsyncTableModel = (function(_super) {
    __extends(PagedAsyncTableModel, _super);

    function PagedAsyncTableModel(cacheSize) {
      if (cacheSize == null) {
        cacheSize = 100;
      }
      this.pageCache = new LRUCache(cacheSize);
      this.columnHeaderPageCache = new LRUCache(cacheSize);
      this.rowHeaderPageCache = new LRUCache(cacheSize);
      this.fetchCallbacks = {};
      this.columnHeaderFetchCallbacks = {};
      this.rowHeaderFetchCallbacks = {};
    }

    PagedAsyncTableModel.prototype.cellPageName = function(i, j) {};

    PagedAsyncTableModel.prototype.columnHeaderPageName = function(j) {};

    PagedAsyncTableModel.prototype.rowHeaderPageName = function(i) {};

    PagedAsyncTableModel.prototype.getColumnHeader = function(j) {
      var pageName;
      pageName = this.columnHeaderPageName(j);
      if (this.columnHeaderPageCache.has(pageName)) {
        return cb(this.columnHeaderPageCache.get(pageName)(j));
      } else if (this.columnHeaderFetchCallbacks[pageName] != null) {
        return this.columnHeaderFetchCallbacks[pageName].push([j, cb]);
      } else {
        this.columnHeaderFetchCallbacks[pageName] = [[j, cb]];
        return this.fetchColumnHeaderPage(pageName, (function(_this) {
          return function(page) {
            var cb, _i, _len, _ref, _ref1;
            _this.columnHeaderPageCache.set(pageName, page);
            _ref = _this.columnHeaderFetchCallbacks[pageName];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              _ref1 = _ref[_i], j = _ref1[0], cb = _ref1[1];
              cb(page(j));
            }
            return delete _this.columnHeaderFetchCallbacks[pageName];
          };
        })(this));
      }
    };

    PagedAsyncTableModel.prototype.getRowHeader = function(i) {
      var pageName;
      pageName = this.rowHeaderPageName(i);
      if (this.rowHeaderPageCache.has(pageName)) {
        return cb(this.rowHeaderPageCache.get(pageName)(i));
      } else if (this.rowHeaderFetchCallbacks[pageName] != null) {
        return this.rowHeaderFetchCallbacks[pageName].push([i, cb]);
      } else {
        this.rowHeaderFetchCallbacks[pageName] = [[i, cb]];
        return this.fetchRowHeaderPage(pageName, (function(_this) {
          return function(page) {
            var cb, _i, _len, _ref, _ref1;
            _this.rowHeaderPageCache.set(pageName, page);
            _ref = _this.rowHeaderFetchCallbacks[pageName];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              _ref1 = _ref[_i], i = _ref1[0], cb = _ref1[1];
              cb(page(i));
            }
            return delete _this.rowHeaderFetchCallbacks[pageName];
          };
        })(this));
      }
    };

    PagedAsyncTableModel.prototype.hasCell = function(i, j) {
      var pageName;
      pageName = this.cellPageName(i, j);
      return this.pageCache.has(pageName);
    };

    PagedAsyncTableModel.prototype.getCell = function(i, j, cb) {
      var pageName;
      if (cb == null) {
        cb = (function() {});
      }
      pageName = this.cellPageName(i, j);
      if (this.pageCache.has(pageName)) {
        return cb(this.pageCache.get(pageName)(i, j));
      } else if (this.fetchCallbacks[pageName] != null) {
        return this.fetchCallbacks[pageName].push([i, j, cb]);
      } else {
        this.fetchCallbacks[pageName] = [[i, j, cb]];
        return this.fetchCellPage(pageName, (function(_this) {
          return function(page) {
            var _i, _len, _ref, _ref1;
            _this.pageCache.set(pageName, page);
            _ref = _this.fetchCallbacks[pageName];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              _ref1 = _ref[_i], i = _ref1[0], j = _ref1[1], cb = _ref1[2];
              cb(page(i, j));
            }
            return delete _this.fetchCallbacks[pageName];
          };
        })(this));
      }
    };

    PagedAsyncTableModel.prototype.fetchCellPage = function(pageName, cb) {};

    PagedAsyncTableModel.prototype.fetchColumnHeaderPage = function(pageName, cb) {};

    PagedAsyncTableModel.prototype.fetchRowHeaderPage = function(pageName, cb) {};

    return PagedAsyncTableModel;

  })(TableModel);

  Painter = (function() {
    function Painter() {}

    Painter.prototype.setupCell = function(cellDiv) {};

    Painter.prototype.setupColumnHeader = function(headerDiv) {};

    Painter.prototype.setupRowHeader = function(headerDiv) {};

    Painter.prototype.cleanUpCell = function(cellDiv) {};

    Painter.prototype.cleanUpColumnHeader = function(headerDiv) {};

    Painter.prototype.cleanUpRowHeader = function(headerDiv) {};

    Painter.prototype.cleanUp = function(table) {
      var cell, header, _, _ref, _ref1, _ref2, _results;
      _ref = table.cells;
      for (_ in _ref) {
        cell = _ref[_];
        this.cleanUpCell(cell);
      }
      _ref1 = table.columns;
      for (_ in _ref1) {
        header = _ref1[_];
        this.cleanUpColumnHeader(header);
      }
      _ref2 = table.rows;
      _results = [];
      for (_ in _ref2) {
        header = _ref2[_];
        _results.push(this.cleanUpRowHeader(header));
      }
      return _results;
    };

    Painter.prototype.fillColumnHeader = function(headerDiv, data) {
      return headerDiv.textContent = data;
    };

    Painter.prototype.fillRowHeader = function(headerDiv, data) {
      return headerDiv.textContent = data;
    };

    Painter.prototype.fillCell = function(cellDiv, data) {
      return cellDiv.textContent = data;
    };

    Painter.prototype.fillColumnHeaderPending = function(headerDiv) {
      return headerDiv.textContent = "NA";
    };

    Painter.prototype.fillRowHeaderPending = function(headerDiv) {
      return headerDiv.textContent = "NA";
    };

    Painter.prototype.fillCellPending = function(cellDiv) {
      return cellDiv.textContent = "NA";
    };

    return Painter;

  })();

  EventRegister = (function() {
    function EventRegister() {
      this.boundEvents = [];
    }

    EventRegister.prototype.bind = function(target, event, cb) {
      this.boundEvents.push([target, event, cb]);
      return target.addEventListener(event, cb);
    };

    EventRegister.prototype.unbindAll = function() {
      var cb, event, target, _i, _len, _ref, _ref1;
      _ref = this.boundEvents;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], target = _ref1[0], event = _ref1[1], cb = _ref1[2];
        target.removeEventListener(event, cb);
      }
      return this.boundEvents = [];
    };

    return EventRegister;

  })();

  ScrollBarProxy = (function() {
    function ScrollBarProxy(bodyContainer, columnHeaderContainer, rowHeaderContainer, totalWidth, totalHeight, eventRegister, horizontalScrollbarVisible, verticalScrollbarVisible, enableDragMove) {
      var bigContentHorizontal, bigContentVertical, getDelta, onMouseWheel, onMouseWheelColumnHeader, onMouseWheelRowHeader, onTouchEnd, onTouchMove, onTouchStart, supportedEvent;
      this.bodyContainer = bodyContainer;
      this.columnHeaderContainer = columnHeaderContainer;
      this.rowHeaderContainer = rowHeaderContainer;
      this.totalWidth = totalWidth;
      this.totalHeight = totalHeight;
      this.horizontalScrollbarVisible = horizontalScrollbarVisible != null ? horizontalScrollbarVisible : true;
      this.verticalScrollbarVisible = verticalScrollbarVisible != null ? verticalScrollbarVisible : true;
      this.enableDragMove = enableDragMove != null ? enableDragMove : true;
      this.verticalScrollbar = document.createElement("div");
      this.verticalScrollbar.className += " fattable-v-scrollbar";
      if (!this.verticalScrollbarVisible) {
        this.verticalScrollbar.style.visibility = "hidden";
      }
      this.horizontalScrollbar = document.createElement("div");
      this.horizontalScrollbar.className += " fattable-h-scrollbar";
      if (!this.horizontalScrollbarVisible) {
        this.horizontalScrollbar.style.visibility = "hidden";
      }
      this.bodyContainer.appendChild(this.horizontalScrollbar);
      this.bodyContainer.appendChild(this.verticalScrollbar);
      bigContentHorizontal = document.createElement("div");
      bigContentHorizontal.style.height = 1 + "px";
      bigContentHorizontal.style.width = this.totalWidth + "px";
      bigContentVertical = document.createElement("div");
      bigContentVertical.style.width = 1 + "px";
      bigContentVertical.style.height = this.totalHeight + "px";
      this.horizontalScrollbar.appendChild(bigContentHorizontal);
      this.verticalScrollbar.appendChild(bigContentVertical);
      this.scrollbarMargin = Math.max(this.horizontalScrollbar.offsetHeight, this.verticalScrollbar.offsetWidth);
      this.verticalScrollbar.style.bottom = this.scrollbarMargin + "px";
      this.horizontalScrollbar.style.right = this.scrollbarMargin + "px";
      this.scrollLeft = 0;
      this.scrollTop = 0;
      this.horizontalScrollbar.onscroll = (function(_this) {
        return function() {
          if (!_this.dragging) {
            if (_this.scrollLeft !== _this.horizontalScrollbar.scrollLeft) {
              _this.scrollLeft = _this.horizontalScrollbar.scrollLeft;
              return _this.onScroll(_this.scrollLeft, _this.scrollTop);
            }
          }
        };
      })(this);
      this.verticalScrollbar.onscroll = (function(_this) {
        return function() {
          if (!_this.dragging) {
            if (_this.scrollTop !== _this.verticalScrollbar.scrollTop) {
              _this.scrollTop = _this.verticalScrollbar.scrollTop;
              return _this.onScroll(_this.scrollLeft, _this.scrollTop);
            }
          }
        };
      })(this);
      if (this.enableDragMove) {
        eventRegister.bind(this.bodyContainer, 'mousedown', (function(_this) {
          return function(event) {
            if (event.button === 1) {
              _this.dragging = true;
              _this.bodyContainer.className = "fattable-body-container fattable-moving";
              _this.dragging_dX = _this.scrollLeft + event.clientX;
              return _this.dragging_dY = _this.scrollTop + event.clientY;
            }
          };
        })(this));
        eventRegister.bind(this.bodyContainer, 'mouseup', (function(_this) {
          return function(event) {
            _this.dragging = false;
            return _this.bodyContainer.className = "fattable-body-container";
          };
        })(this));
        eventRegister.bind(this.bodyContainer, 'mousemove', (function(_this) {
          return function(event) {
            var deferred;
            deferred = function() {
              var newX, newY;
              if (_this.dragging) {
                newX = -event.clientX + _this.dragging_dX;
                newY = -event.clientY + _this.dragging_dY;
                return _this.setScrollXY(newX, newY);
              }
            };
            return window.setTimeout(deferred, 0);
          };
        })(this));
        eventRegister.bind(this.bodyContainer, 'mouseout', (function(_this) {
          return function(event) {
            if (_this.dragging) {
              if ((event.toElement == null) || (event.toElement.parentElement.parentElement !== _this.bodyContainer)) {
                _this.bodyContainer.className = "fattable-body-container";
                return _this.dragging = false;
              }
            }
          };
        })(this));
        eventRegister.bind(this.columnHeaderContainer, 'mousedown', (function(_this) {
          return function(event) {
            if (event.button === 1) {
              _this.columnHeaderDragging = true;
              _this.columnHeaderContainer.className = "fattable-header-container fattable-column-header-container fattable-moving";
              return _this.dragging_dX = _this.scrollLeft + event.clientX;
            }
          };
        })(this));
        eventRegister.bind(this.rowHeaderContainer, 'mousedown', (function(_this) {
          return function(event) {
            if (event.button === 1) {
              _this.rowHeaderDragging = true;
              _this.rowHeaderContainer.className = "fattable-header-container fattable-row-header-container fattable-moving";
              return _this.dragging_dY = _this.scrollTop + event.clientY;
            }
          };
        })(this));
        eventRegister.bind(this.bodyContainer, 'mouseup', (function(_this) {
          return function(event) {
            var captureClick;
            if (event.button === 1) {
              _this.columnHeaderDragging = false;
              _this.rowHeaderDragging = false;
              _this.columnHeaderContainer.className = "fattable-header-container";
              event.stopPropagation();
              captureClick = function(e) {
                e.stopPropagation();
                return this.removeEventListener('click', captureClick, true);
              };
              return _this.bodyContainer.addEventListener('click', captureClick, true);
            }
          };
        })(this));
        eventRegister.bind(this.columnHeaderContainer, 'mousemove', (function(_this) {
          return function(event) {
            var deferred;
            deferred = function() {
              var newX;
              if (_this.columnHeaderDragging) {
                newX = -event.clientX + _this.dragging_dX;
                return _this.setScrollXY(newX);
              }
            };
            return window.setTimeout(deferred, 0);
          };
        })(this));
        eventRegister.bind(this.columnHeaderContainer, 'mouseout', (function(_this) {
          return function(event) {
            if (_this.columnHeaderDragging) {
              if ((event.toElement == null) || (event.toElement.parentElement.parentElement !== _this.columnHeaderContainer)) {
                _this.columnHeaderContainer.className = "fattable-header-container fattable-column-header-container";
              }
              return _this.columnHeaderDragging = false;
            }
          };
        })(this));
        eventRegister.bind(this.rowHeaderContainer, 'mousemove', (function(_this) {
          return function(event) {
            var deferred;
            deferred = function() {
              var newY;
              if (_this.rowHeaderDragging) {
                newY = -event.clientY + _this.dragging_dY;
                return _this.setScrollXY(void 0, newY);
              }
            };
            return window.setTimeout(deferred, 0);
          };
        })(this));
        eventRegister.bind(this.rowHeaderContainer, 'mouseout', (function(_this) {
          return function(event) {
            if (_this.rowHeaderDragging) {
              if ((event.toElement == null) || (event.toElement.parentElement.parentElement !== _this.rowHeaderContainer)) {
                _this.rowHeaderContainer.className = "fattable-header-container fattable-row-header-container";
              }
              return _this.rowHeaderDragging = false;
            }
          };
        })(this));
      }
      if (this.totalWidth > this.horizontalScrollbar.clientWidth) {
        this.maxScrollHorizontal = this.totalWidth - this.horizontalScrollbar.clientWidth;
      } else {
        this.maxScrollHorizontal = 0;
      }
      if (this.totalHeight > this.verticalScrollbar.clientHeight) {
        this.maxScrollVertical = this.totalHeight - this.verticalScrollbar.clientHeight;
      } else {
        this.maxScrollVertical = 0;
      }
      supportedEvent = "DOMMouseScroll";
      if (this.bodyContainer.onwheel !== void 0) {
        supportedEvent = "wheel";
      } else if (this.bodyContainer.onmousewheel !== void 0) {
        supportedEvent = "mousewheel";
      }
      getDelta = (function() {
        switch (supportedEvent) {
          case "wheel":
            return function(event) {
              var deltaX, deltaY, _ref, _ref1, _ref2, _ref3;
              switch (event.deltaMode) {
                case event.DOM_DELTA_LINE:
                  deltaX = (_ref = -50 * event.deltaX) != null ? _ref : 0;
                  deltaY = (_ref1 = -50 * event.deltaY) != null ? _ref1 : 0;
                  break;
                case event.DOM_DELTA_PIXEL:
                  deltaX = (_ref2 = -1 * event.deltaX) != null ? _ref2 : 0;
                  deltaY = (_ref3 = -1 * event.deltaY) != null ? _ref3 : 0;
              }
              return [deltaX, deltaY];
            };
          case "mousewheel":
            return function(event) {
              var deltaX, deltaY, _ref, _ref1;
              deltaX = 0;
              deltaY = 0;
              deltaX = (_ref = event.wheelDeltaX) != null ? _ref : 0;
              deltaY = (_ref1 = event.wheelDeltaY) != null ? _ref1 : event.wheelDelta;
              return [deltaX, deltaY];
            };
          case "DOMMouseScroll":
            return function(event) {
              var deltaX, deltaY;
              deltaX = 0;
              deltaY = 0;
              if (event.axis === event.HORIZONTAL_AXI) {
                deltaX = -50.0 * event.detail;
              } else {
                deltaY = -50.0 * event.detail;
              }
              return [deltaX, deltaY];
            };
        }
      })();
      onMouseWheel = (function(_this) {
        return function(event) {
          var deltaX, deltaY, has_scrolled, _ref;
          _ref = getDelta(event), deltaX = _ref[0], deltaY = _ref[1];
          has_scrolled = _this.setScrollXY(_this.scrollLeft - deltaX, _this.scrollTop - deltaY);
          if (has_scrolled) {
            return event.preventDefault();
          }
        };
      })(this);
      onMouseWheelColumnHeader = (function(_this) {
        return function(event) {
          var deltaX, has_scrolled, _, _ref;
          _ref = getDelta(event), deltaX = _ref[0], _ = _ref[1];
          has_scrolled = _this.setScrollXY(_this.scrollLeft - deltaX, _this.scrollTop);
          if (has_scrolled) {
            return event.preventDefault();
          }
        };
      })(this);
      onMouseWheelRowHeader = (function(_this) {
        return function(event) {
          var deltaY, has_scrolled, _, _ref;
          _ref = getDelta(event), _ = _ref[0], deltaY = _ref[1];
          has_scrolled = _this.setScrollXY(_this.scrollLeft, _this.scrollTop - deltaY);
          if (has_scrolled) {
            return event.preventDefault();
          }
        };
      })(this);
      eventRegister.bind(this.bodyContainer, supportedEvent, onMouseWheel);
      eventRegister.bind(this.columnHeaderContainer, supportedEvent, onMouseWheelColumnHeader);
      eventRegister.bind(this.rowHeaderContainer, supportedEvent, onMouseWheelRowHeader);
      this.scroller = new Scroller(this.setScrollXY.bind(this), {});
      this.scroller.setDimensions(this.scrollWidth, this.scrollHeight, this.totalWidth, this.totalHeight);
      onTouchStart = (function(_this) {
        return function(event) {
          _this.__isTouchDown = true;
          _this.scroller.doTouchStart(getEventTouches(event), event.timeStamp);
          return event.preventDefault();
        };
      })(this);
      onTouchMove = (function(_this) {
        return function(event) {
          _this.scroller.doTouchMove(getEventTouches(event), event.timeStamp, event.scale);
          return _this.__isTouchDown = true;
        };
      })(this);
      onTouchEnd = (function(_this) {
        return function(event) {
          if (!_this.__isTouchDown) {
            return;
          }
          _this.scroller.doTouchEnd(event.timeStamp);
          return _this.__isTouchDown = false;
        };
      })(this);
      if ('ontouchstart' in window) {
        eventRegister.bind(this.bodyContainer, "touchstart", onTouchStart);
        eventRegister.bind(this.bodyContainer, "touchmove", onTouchMove);
        eventRegister.bind(this.bodyContainer, "touchend", onTouchEnd);
        eventRegister.bind(this.bodyContainer, "touchcancel", onTouchEnd);
      } else if (window.navigator.pointerEnabled) {
        eventRegister.bind(this.bodyContainer, "pointerdown", onTouchStart);
        eventRegister.bind(this.bodyContainer, "pointermove", onTouchMove);
        eventRegister.bind(this.bodyContainer, "pointerup", onTouchEnd);
        eventRegister.bind(this.bodyContainer, "pointercancel", onTouchEnd);
      } else if (window.navigator.msPointerEnabled) {
        eventRegister.bind(this.bodyContainer, "MSPointerDown", onTouchStart);
        eventRegister.bind(this.bodyContainer, "MSPointerMove", onTouchMove);
        eventRegister.bind(this.bodyContainer, "MSPointerUp", onTouchEnd);
        eventRegister.bind(this.bodyContainer, "MSPointerCancel", onTouchEnd);
      }
    }

    ScrollBarProxy.prototype.onScroll = function(x, y) {};

    ScrollBarProxy.prototype.setScrollXY = function(x, y) {
      var has_scrolled;
      has_scrolled = false;
      if (x != null) {
        x = bound(x, 0, this.maxScrollHorizontal);
        if (this.scrollLeft !== x) {
          has_scrolled = true;
          this.scrollLeft = x;
        }
      } else {
        x = this.scrollLeft;
      }
      if (y != null) {
        y = bound(y, 0, this.maxScrollVertical);
        if (this.scrollTop !== y) {
          has_scrolled = true;
          this.scrollTop = y;
        }
      } else {
        y = this.scrollTop;
      }
      this.horizontalScrollbar.scrollLeft = x;
      this.verticalScrollbar.scrollTop = y;
      this.onScroll(x, y);
      return has_scrolled;
    };

    return ScrollBarProxy;

  })();

  TableView = (function() {
    function TableView(parameters) {
      var container;
      container = parameters.container;
      if (container == null) {
        throw "container not specified.";
      }
      if (typeof container === "string") {
        this.container = document.querySelector(container);
      } else if (typeof container === "object") {
        this.container = container;
      } else {
        throw "Container must be a string or a dom element.";
      }
      this._readRequiredParameter(parameters, "painter", new Painter());
      this._readRequiredParameter(parameters, "autoSetup", true);
      this._readRequiredParameter(parameters, "model");
      this._readRequiredParameter(parameters, "nbRows");
      this._readRequiredParameter(parameters, "rowHeight");
      this._readRequiredParameter(parameters, "columnWidths");
      this._readRequiredParameter(parameters, "nbColsOverdraw", 2);
      this._readRequiredParameter(parameters, "nbRowsOverdraw", 2);
      this._readRequiredParameter(parameters, "columnHeaderHeight");
      this._readRequiredParameter(parameters, "rowHeaderWidth");
      this._readRequiredParameter(parameters, "scrollBarVisible", true);
      this._readRequiredParameter(parameters, "horizontalScrollbar", this.scrollBarVisible);
      this._readRequiredParameter(parameters, "verticalScrollbar", this.scrollBarVisible);
      this._readRequiredParameter(parameters, "enableDragMove", true);
      this.nbCols = this.columnWidths.length;
      if ((" " + this.container.className + " ").search(/\sfattable\s/) === -1) {
        this.container.className += " fattable";
      }
      this.totalHeight = this.rowHeight * this.nbRows;
      this.columnOffset = cumsum(this.columnWidths);
      this.totalWidth = this.columnOffset[this.columnOffset.length - 1];
      this.rows = {};
      this.columns = {};
      this.cells = {};
      this.eventRegister = new EventRegister();
      this.calculateContainerDimensions();
      if (this.autoSetup) {
        this.setup();
      }
    }

    TableView.prototype._readRequiredParameter = function(parameters, k, default_value) {
      if (parameters[k] == null) {
        if (default_value === void 0) {
          throw "Expected parameter <" + k + ">";
        } else {
          return this[k] = default_value;
        }
      } else {
        return this[k] = parameters[k];
      }
    };

    TableView.prototype.calculateContainerDimensions = function() {
      this.scrollWidth = this.container.offsetWidth - this.rowHeaderWidth;
      this.scrollHeight = this.container.offsetHeight - this.columnHeaderHeight;
      this.nbColsVisible = Math.min(smallest_diff_subsequence(this.columnOffset, this.scrollWidth) + this.nbColsOverdraw, this.columnWidths.length);
      this.nbRowsVisible = Math.min((this.scrollHeight / this.rowHeight | 0) + this.nbRowsOverdraw, this.nbRows);
      if (this.totalWidth <= this.scrollWidth) {
        this.horizontalScrollbar = false;
      }
      if (this.totalHeight <= this.scrollHeight) {
        return this.verticalScrollbar = false;
      }
    };

    TableView.prototype._findLeftTopCornerAtXY = function(x, y) {
      var i, j;
      i = bound(y / this.rowHeight | 0, 0, this.nbRows - this.nbRowsVisible);
      j = bound(binary_search(this.columnOffset, x), 0, this.nbCols - this.nbColsVisible);
      return [i, j];
    };

    TableView.prototype.cleanUp = function() {
      var _ref;
      this.eventRegister.unbindAll();
      if ((_ref = this.scrollProxy) != null) {
        _ref.onScroll = null;
      }
      this.painter.cleanUp(this);
      this.container.innerHTML = "";
      this.bodyContainer = null;
      this.columnHeaderContainer = null;
      return this.rowHeaderContainer = null;
    };

    TableView.prototype.setup = function() {
      var el, i, j, _i, _j, _k, _l, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
      this.cleanUp();
      this.calculateContainerDimensions();
      this.columns = {};
      this.rows = {};
      this.cells = {};
      this.container.innerHTML = "";
      this.columnHeaderContainer = document.createElement("div");
      this.columnHeaderContainer.className += " fattable-header-container fattable-column-header-container";
      this.columnHeaderContainer.style.width = this.scrollWidth + "px";
      this.columnHeaderContainer.style.height = this.columnHeaderHeight + "px";
      this.columnHeaderContainer.style.left = this.rowHeaderWidth + "px";
      this.columnHeaderViewport = document.createElement("div");
      this.columnHeaderViewport.className = "fattable-viewport";
      this.columnHeaderViewport.style.height = this.columnHeaderHeight + "px";
      this.columnHeaderContainer.appendChild(this.columnHeaderViewport);
      this.rowHeaderContainer = document.createElement("div");
      this.rowHeaderContainer.className += " fattable-header-container fattable-row-header-container";
      this.rowHeaderContainer.style.height = this.scrollHeight + "px";
      this.rowHeaderContainer.style.width = this.rowHeaderWidth + "px";
      this.rowHeaderContainer.style.top = this.columnHeaderHeight + "px";
      this.rowHeaderViewport = document.createElement("div");
      this.rowHeaderViewport.className = "fattable-viewport";
      this.rowHeaderContainer.appendChild(this.rowHeaderViewport);
      this.bodyContainer = document.createElement("div");
      this.bodyContainer.className = "fattable-body-container";
      this.bodyContainer.style.width = this.scrollWidth + "px";
      this.bodyContainer.style.top = this.columnHeaderHeight + "px";
      this.bodyContainer.style.left = this.rowHeaderWidth + "px";
      this.bodyViewport = document.createElement("div");
      this.bodyViewport.className = "fattable-viewport";
      this.bodyViewport.style.height = this.scrollHeight + "px";
      for (j = _i = _ref = this.nbColsVisible, _ref1 = this.nbColsVisible * 2; _i < _ref1; j = _i += 1) {
        el = document.createElement("div");
        el.style.height = this.columnHeaderHeight + "px";
        el.pending = false;
        this.painter.setupColumnHeader(el);
        this.columns[j] = el;
        this.columnHeaderViewport.appendChild(el);
      }
      for (i = _j = _ref2 = this.nbRowsVisible, _ref3 = this.nbRowsVisible * 2; _j < _ref3; i = _j += 1) {
        el = document.createElement("div");
        el.style.width = this.rowHeaderWidth + "px";
        el.pending = false;
        this.painter.setupRowHeader(el);
        this.rows[i] = el;
        this.rowHeaderViewport.appendChild(el);
      }
      for (j = _k = _ref4 = this.nbColsVisible, _ref5 = this.nbColsVisible * 2; _k < _ref5; j = _k += 1) {
        for (i = _l = _ref6 = this.nbRowsVisible, _ref7 = this.nbRowsVisible * 2; _l < _ref7; i = _l += 1) {
          el = document.createElement("div");
          this.painter.setupCell(el);
          el.pending = false;
          el.style.height = this.rowHeight + "px";
          this.bodyViewport.appendChild(el);
          this.cells[i + "," + j] = el;
        }
      }
      this.firstVisibleRow = this.nbRowsVisible;
      this.firstVisibleColumn = this.nbColsVisible;
      this.display(0, 0);
      this.container.appendChild(this.bodyContainer);
      this.container.appendChild(this.columnHeaderContainer);
      this.container.appendChild(this.rowHeaderContainer);
      this.bodyContainer.appendChild(this.bodyViewport);
      this.refreshAllContent();
      this.scrollProxy = new ScrollBarProxy(this.bodyContainer, this.columnHeaderContainer, this.rowHeaderContainer, this.totalWidth, this.totalHeight, this.eventRegister, this.horizontalScrollbar, this.verticalScrollbar, this.enableDragMove);
      this.scrollProxy.onScroll = (function(_this) {
        return function(x, y) {
          var cell, col, row, _, _ref10, _ref11, _ref8, _ref9;
          _ref8 = _this._findLeftTopCornerAtXY(x, y), i = _ref8[0], j = _ref8[1];
          _this.display(i, j);
          _ref9 = _this.cells;
          for (_ in _ref9) {
            cell = _ref9[_];
            cell.style[prefixedTransformCssKey] = "translate(" + (cell.left - x) + "px," + (cell.top - y) + "px)";
          }
          _ref10 = _this.columns;
          for (_ in _ref10) {
            col = _ref10[_];
            col.style[prefixedTransformCssKey] = "translate(" + (col.left - x) + "px, 0px)";
          }
          _ref11 = _this.rows;
          for (_ in _ref11) {
            row = _ref11[_];
            row.style[prefixedTransformCssKey] = "translate(0px, " + (row.top - y) + "px)";
          }
          clearTimeout(_this.scrollEndTimer);
          _this.scrollEndTimer = setTimeout(_this.refreshAllContent.bind(_this), 200);
          return _this.onScroll(x, y);
        };
      })(this);
      return this.scrollProxy.onScroll(0, 0);
    };

    TableView.prototype.resize = function() {
      var scrollLeft, scrollTop, _ref;
      _ref = this.scrollProxy, scrollLeft = _ref.scrollLeft, scrollTop = _ref.scrollTop;
      this.setup();
      return this.scrollProxy.setScrollXY(scrollLeft, scrollTop);
    };

    TableView.prototype.refreshAllContent = function(evenNotPending) {
      var cell, columnHeader, i, j, k, rowHeader, _fn, _i, _j, _k, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _results;
      if (evenNotPending == null) {
        evenNotPending = false;
      }
      _fn = (function(_this) {
        return function(columnHeader) {
          if (evenNotPending || columnHeader.pending) {
            return _this.model.getColumnHeader(j, function(data) {
              columnHeader.pending = false;
              return _this.painter.fillColumnHeader(columnHeader, data);
            });
          }
        };
      })(this);
      for (j = _i = _ref = this.firstVisibleColumn, _ref1 = this.firstVisibleColumn + this.nbColsVisible; _i < _ref1; j = _i += 1) {
        columnHeader = this.columns[j];
        _fn(columnHeader);
        for (i = _j = _ref2 = this.firstVisibleRow, _ref3 = this.firstVisibleRow + this.nbRowsVisible; _j < _ref3; i = _j += 1) {
          k = i + "," + j;
          cell = this.cells[k];
          if (evenNotPending || cell.pending) {
            (function(_this) {
              return (function(cell) {
                return _this.model.getCell(i, j, function(data) {
                  cell.pending = false;
                  return _this.painter.fillCell(cell, data);
                });
              });
            })(this)(cell);
          }
        }
      }
      _results = [];
      for (i = _k = _ref4 = this.firstVisibleRow, _ref5 = this.firstVisibleRow + this.nbRowsVisible; _k < _ref5; i = _k += 1) {
        rowHeader = this.rows[i];
        _results.push((function(_this) {
          return function(rowHeader) {
            if (evenNotPending || rowHeader.pending) {
              return _this.model.getRowHeader(i, function(data) {
                rowHeader.pending = false;
                return _this.painter.fillRowHeader(rowHeader, data);
              });
            }
          };
        })(this)(rowHeader));
      }
      return _results;
    };

    TableView.prototype.onScroll = function(x, y) {};

    TableView.prototype.goTo = function(i, j) {
      var targetX, targetY;
      targetY = i != null ? this.rowHeight * i : void 0;
      targetX = j != null ? this.columnOffset[j] : void 0;
      return this.scrollProxy.setScrollXY(targetX, targetY);
    };

    TableView.prototype.display = function(i, j) {
      this.columnHeaderContainer.style.display = "none";
      this.rowHeaderContainer.style.display = "none";
      this.bodyContainer.style.display = "none";
      this.moveX(j);
      this.moveY(i);
      this.columnHeaderContainer.style.display = "";
      this.rowHeaderContainer.style.display = "";
      return this.bodyContainer.style.display = "";
    };

    TableView.prototype.moveX = function(j) {
      var cell, col_width, col_x, columnHeader, dest_j, dj, i, k, last_i, last_j, offset_j, orig_j, shift_j, _fn, _i, _j, _ref;
      last_i = this.firstVisibleRow;
      last_j = this.firstVisibleColumn;
      shift_j = j - last_j;
      if (shift_j === 0) {
        return;
      }
      dj = Math.min(Math.abs(shift_j), this.nbColsVisible);
      for (offset_j = _i = 0; _i < dj; offset_j = _i += 1) {
        if (shift_j > 0) {
          orig_j = this.firstVisibleColumn + offset_j;
          dest_j = j + offset_j + this.nbColsVisible - dj;
        } else {
          orig_j = this.firstVisibleColumn + this.nbColsVisible - dj + offset_j;
          dest_j = j + offset_j;
        }
        col_x = this.columnOffset[dest_j];
        col_width = this.columnWidths[dest_j] + "px";
        columnHeader = this.columns[orig_j];
        delete this.columns[orig_j];
        if (this.model.hasColumnHeader(dest_j)) {
          this.model.getColumnHeader(dest_j, (function(_this) {
            return function(data) {
              columnHeader.pending = false;
              return _this.painter.fillColumnHeader(columnHeader, data);
            };
          })(this));
        } else if (!columnHeader.pending) {
          columnHeader.pending = true;
          this.painter.fillColumnHeaderPending(columnHeader);
        }
        columnHeader.left = col_x;
        columnHeader.style.width = col_width;
        this.columns[dest_j] = columnHeader;
        _fn = (function(_this) {
          return function(cell) {
            if (_this.model.hasCell(i, dest_j)) {
              return _this.model.getCell(i, dest_j, function(data) {
                cell.pending = false;
                return _this.painter.fillCell(cell, data);
              });
            } else if (!cell.pending) {
              cell.pending = true;
              return _this.painter.fillCellPending(cell);
            }
          };
        })(this);
        for (i = _j = last_i, _ref = last_i + this.nbRowsVisible; _j < _ref; i = _j += 1) {
          k = i + "," + orig_j;
          cell = this.cells[k];
          delete this.cells[k];
          this.cells[i + "," + dest_j] = cell;
          cell.left = col_x;
          cell.style.width = col_width;
          _fn(cell);
        }
      }
      return this.firstVisibleColumn = j;
    };

    TableView.prototype.moveY = function(i) {
      var cell, dest_i, di, j, k, last_i, last_j, offset_i, orig_i, rowHeader, row_y, shift_i, _fn, _i, _j, _ref;
      last_i = this.firstVisibleRow;
      last_j = this.firstVisibleColumn;
      shift_i = i - last_i;
      if (shift_i === 0) {
        return;
      }
      di = Math.min(Math.abs(shift_i), this.nbRowsVisible);
      for (offset_i = _i = 0; _i < di; offset_i = _i += 1) {
        if (shift_i > 0) {
          orig_i = this.firstVisibleRow + offset_i;
          dest_i = i + offset_i + this.nbRowsVisible - di;
        } else {
          orig_i = this.firstVisibleRow + this.nbRowsVisible - di + offset_i;
          dest_i = i + offset_i;
        }
        row_y = dest_i * this.rowHeight;
        rowHeader = this.rows[orig_i];
        delete this.rows[orig_i];
        if (this.model.hasRowHeader(dest_i)) {
          this.model.getRowHeader(dest_i, (function(_this) {
            return function(data) {
              rowHeader.pending = false;
              return _this.painter.fillRowHeader(rowHeader, data);
            };
          })(this));
        } else if (!rowHeader.pending) {
          rowHeader.pending = true;
          this.painter.fillRowHeaderPending(rowHeader);
        }
        rowHeader.top = row_y;
        this.rows[dest_i] = rowHeader;
        _fn = (function(_this) {
          return function(cell) {
            if (_this.model.hasCell(dest_i, j)) {
              return _this.model.getCell(dest_i, j, function(data) {
                cell.pending = false;
                return _this.painter.fillCell(cell, data);
              });
            } else if (!cell.pending) {
              cell.pending = true;
              return _this.painter.fillCellPending(cell);
            }
          };
        })(this);
        for (j = _j = last_j, _ref = last_j + this.nbColsVisible; _j < _ref; j = _j += 1) {
          k = orig_i + "," + j;
          cell = this.cells[k];
          delete this.cells[k];
          this.cells[dest_i + "," + j] = cell;
          cell.top = row_y;
          _fn(cell);
        }
      }
      return this.firstVisibleRow = i;
    };

    return TableView;

  })();

  fattable = function(params) {
    return new TableView(params);
  };

  ns = {
    TableModel: TableModel,
    TableView: TableView,
    Painter: Painter,
    PagedAsyncTableModel: PagedAsyncTableModel,
    SyncTableModel: SyncTableModel
  };

  for (k in ns) {
    v = ns[k];
    fattable[k] = v;
  }

  window.fattable = fattable;

}).call(this);
